// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1U6_Q_ZK_PpsQLOpnK7k-IgEE7zkDVmM',
    appId: '1:1094366148865:web:81577da6ec1dc48b6f0300',
    messagingSenderId: '1094366148865',
    projectId: 'highproteinchef-4f9ec',
    authDomain: 'highproteinchef-4f9ec.firebaseapp.com',
    storageBucket: 'highproteinchef-4f9ec.appspot.com',
    measurementId: 'G-HQPK3G89DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAt8G1z--KfZBTRi98_hTrq6Lam1gpN4',
    appId: '1:1094366148865:android:52c96f89081ccceb6f0300',
    messagingSenderId: '1094366148865',
    projectId: 'highproteinchef-4f9ec',
    storageBucket: 'highproteinchef-4f9ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OEbAFzbao112O7mkHlfk8HtjQ_iea5I',
    appId: '1:1094366148865:ios:891048e4fc5746046f0300',
    messagingSenderId: '1094366148865',
    projectId: 'highproteinchef-4f9ec',
    storageBucket: 'highproteinchef-4f9ec.appspot.com',
    iosBundleId: 'com.example.highProteinChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2OEbAFzbao112O7mkHlfk8HtjQ_iea5I',
    appId: '1:1094366148865:ios:891048e4fc5746046f0300',
    messagingSenderId: '1094366148865',
    projectId: 'highproteinchef-4f9ec',
    storageBucket: 'highproteinchef-4f9ec.appspot.com',
    iosBundleId: 'com.example.highProteinChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1U6_Q_ZK_PpsQLOpnK7k-IgEE7zkDVmM',
    appId: '1:1094366148865:web:f0a074da248f6f096f0300',
    messagingSenderId: '1094366148865',
    projectId: 'highproteinchef-4f9ec',
    authDomain: 'highproteinchef-4f9ec.firebaseapp.com',
    storageBucket: 'highproteinchef-4f9ec.appspot.com',
    measurementId: 'G-2MYTRRBK6P',
  );
}
